/* Prüfkorpus für test/vorbehandlung.js. Neue Regel, neuer Fall – vor allem in BLEIBT_EXAKT. */

/* [Eingabe, Zeichenkette, die verschwinden muss] */
const RAUS = [
  ['Ticket 4711 bearbeitet', '4711'],
  ['Störung #10482 behoben', '10482'],
  ['Vorgang [88213] abgeschlossen', '88213'],
  ['INC 12345 geprüft', '12345'],
  ['Auftrag Nr. 883 erledigt', '883'],
  ['Notebook NB1234 neu aufgesetzt', 'NB1234'],
  ['PC-07 in die Domäne aufgenommen', 'PC-07'],
  ['SRV-DC01 neu gestartet', 'SRV-DC01'],
  ['AP12 im Lager montiert', 'AP12'],
  ['Drucker12 ersetzt', 'Drucker12'],
  ['Rücksprache mit Herr Weber', 'Weber'],
  ['Einweisung durch Frau Schmidt gehalten', 'Schmidt'],
  ['Übergabe an M. Weber', 'Weber'],
  ['Mail an info@muster-gmbh.de geschickt', 'muster-gmbh.de'],
  ['Abstimmung mit @mweber', 'mweber'],
  ['Schulung von Max Mustermann erhalten', 'Mustermann'],
  ['Thomas Meier eingewiesen', 'Meier'],
  ['Rücksprache mit Andreas', 'Andreas'],
  ['Arbeitsplatz für Julia Hoffmann eingerichtet', 'Hoffmann'],
];

/* Zeilen, die Wort für Wort so bleiben müssen */
const BLEIBT_EXAKT = [
  // Fächer eines Berufsschultags aus der Zeiterfassung (import/schule.js)
  'AEUP: Datenbanken, Normalisierung',
  'ITT: ESP32',
  'FPP: Cisco Paket Tracer',
  'E: Compiler and Interpreter',
  'LF5: Schleifen und Arrays',
  'WiSo: Tarifvertrag',
  'Ubuntu Server LTS installiert',
  'VLAN-Regeln geprüft',
  'Windows 11 ausgerollt',
  'Windows 10 auf Windows 11 migriert',
  'Windows-10 Image erstellt',
  'Office 365 Lizenzen geprüft',
  'Office-365 Konto angelegt',
  'Exchange 2019 Postfach angelegt',
  'SQL Server 2022 installiert',
  'Windows Server 2022 Domäne eingerichtet',
  'Apache2 installiert',
  'PHP8 eingerichtet',
  'RAID 5 aufgebaut',
  'RAID-10 aufgebaut',
  'Cat 6 Kabel verlegt',
  'Cat-6 Kabel verlegt',
  'USB-Sticks erstellt',
  'USB-C Dockingstation getestet',
  'Port 443 freigegeben',
  'AES256 Verschlüsselung eingerichtet',
  'SHA256 Prüfsumme verglichen',
  'RFC1918 Adressen dokumentiert',
  'ISO9001 Audit vorbereitet',
  'DIN5008 Brief erstellt',
  'IEEE802 Standard gelesen',
  'OneNote-Dokumentation gepflegt',
  'GitLab eingerichtet',
  'IPv6-Sicherheitsregeln gesetzt',
  'LAN-Kabel verlegt',
  'CSV-Import erweitert',
  'Backup mit Veeam getestet',
  'DNS und DHCP konfiguriert',
  'Serverraum begangen',
  'Serverraum 2 aufgeräumt',
  'Raum 204 verkabelt',
  'Switch 24 Port montiert',
  'HP ProBook 450 eingerichtet',
  'Lenovo ThinkPad T14 aufgesetzt',
  'Dell Latitude 5540 Image erstellt',
  'Fritzbox 7590 konfiguriert',
  'Ubiquiti AP installiert',
  'Ticket-System eingerichtet',
  'Change Management dokumentiert',
  'Schulung an Microsoft Exchange',
  'Fehler bei Adobe Reader behoben',
  'Migration von Exchange Online',
  'Test mit Mozilla Firefox',
  'Arbeit an Windows Servern',
  'Analyse von Log Dateien',
  'Doku für Neue Mitarbeiter',
  'Update für Firewall Cluster',
  'Support bei Outlook Problemen',
  'Abstimmung mit IT Leitung',
  'Rücksprache mit Active Directory Team',
  'Zusammenarbeit mit Externem Dienstleister',
  'Einweisung von Neuen Kollegen',
  'Umbau an Alter Hardware',
  'Übergabe an Abteilung Vertrieb',
  'Schulung bei Microsoft Teams',
  'Azure AD Connect geprüft',
  'iPhone 17 eingerichtet',
  'Kabel von A nach B verlegt',
  'Anleitung Schritt für Schritt geschrieben',
  '24/7 Monitoring eingerichtet',
  'Verhältnis 1/3 berechnet',
  'Update auf Version 2.1 eingespielt',
  'Firewall Regel 15 angepasst',
  'Rufumleitung 3CX eingerichtet',
  'M365 Lizenz zugewiesen',
  'W11 Rollout vorbereitet',
  'AD DS eingerichtet',
  'Drucker im 2. OG getauscht',
  'Backup von Mittwoch geprüft',
  'Migration abgeschlossen',
  'Nr. 3 der Checkliste abgearbeitet',
  'z. B. Drucker getauscht',
  'Ubuntu 24.04 installiert',
  'Hyper-V Host gewartet',
  'Anti-Viren-System aktualisiert',
  'E-Mail-Infrastruktur geprüft',
  'IT-Einrichtung für neuen Arbeitsplatz',
  'Server-Härtung dokumentiert',
  'Passwort-Tresor gepflegt',
];

/* [Eingabe, erwartetes Ergebnis] */
const UMFORMEN = [
  ['- Drucker getauscht', 'Drucker getauscht'],
  ['• Netzwerk geprüft', 'Netzwerk geprüft'],
  ['Setup - Installation - Test', 'Setup, Installation, Test'],
  ['Backup --- geprüft', 'Backup geprüft'],
  ['Analyse | Umsetzung', 'Analyse, Umsetzung'],
  ['Planung / Umsetzung', 'Planung, Umsetzung'],
  ['ERLEDIGT: Drucker getauscht', 'Drucker getauscht'],
  ['Drucker getauscht - erledigt', 'Drucker getauscht'],
  ['Netzwerk geprüft (ok)', 'Netzwerk geprüft'],
  ['Ticket 4711: Drucker bei Herr Weber getauscht', 'Ticket: Drucker bei einem Kollegen getauscht'],
  ['Wartung an SRV01 und Backup geprüft', 'Wartung an Server und Backup geprüft'],
  ['Rücksprache mit Herr Weber, danach Doku', 'Rücksprache mit einem Kollegen, danach Doku'],
  ['08:00 - 16:30 Fehlersuche', 'Fehlersuche'],
  ['Besprechung mit Frau Bauer und Herr Klein', 'Besprechung mit Kollegen'],
  ['Gespräch mit Herr Weber und Frau Klein', 'Gespräch mit Kollegen'],
  ['Störung #123  --  behoben,  , geprüft', 'Störung behoben, geprüft'],
  // Anonymisieren statt löschen: der Satz muss ein Satz bleiben
  ['Ticket #149725 gelöst durch Analyse', 'Ticket gelöst durch Analyse'],
  ['Unterstützung von Michael bei einem Ticket', 'Unterstützung von einem Kollegen bei einem Ticket'],
  ['Zertifikatsvalidierung KDNWKS11', 'Zertifikatsvalidierung Arbeitsplatzrechner'],
  ['Zugriff auf KDNSRVEX04 fehlt', 'Zugriff auf Server fehlt'],
  ['Analyse auf PC-ANNA-MINI', 'Analyse auf PC'],
  ['Johannes Hilfe bei Windows Applikation', 'Kollege Hilfe bei Windows Applikation'],
  ['an Johannes weitergeleitet', 'an einen Kollegen weitergeleitet'],
  // Bewusst in Kauf genommen: Ein nach einem Menschen benanntes System trifft es auch.
  ['Lena Server aufgesetzt', 'Kollege Server aufgesetzt'],
];

/* Zeilen, die komplett wegfallen */
const MUELL = ['erledigt', 'ok', '---', 'TODO', 'fertig', 'n/a', 'xxx'];

module.exports = { RAUS, BLEIBT_EXAKT, UMFORMEN, MUELL };
